language: python
cache: pip
python:
- '3.6'
- '3.5'
- '2.7'
- pypy
before_install:
  # Workaround for travis issue
  - pip install -U six
install:
- pip install -r dev-requirements.txt
- pip install -U .
script: invoke test

jobs:
  include:
  - stage: PyPI Release
    if: tag IS present
    python: "3.6"
    # Override before_install, install, and script to no-ops
    before_install: true
    install: true
    script: echo "Releasing to PyPI..."
    after_success: true
    deploy:
      provider: pypi
      user: sloria
      on:
        tags: true
      distributions: sdist bdist_wheel
      password:
        secure: D0c2PYyI06+N5/inLaPHkEaM/GVgKVPCBDm2asmQvCTs14ory9KK17cnS+tOmrTNyMzw2tYSvD1Ar5a7MQAfcJ+p2bOnr/UCLqzt98H2LlE/2NJdzQtI3FtNCkhRVx20LK85G8ZWaHCecGIkgGmbIDZ56u1Aj+G16z0PqEz5i7s=
